schema_version = "1.0.0"
id = "ambientcg_material_importer"
version = "1.1.0"
name = "AmbientCG Material Importer"
tagline = "One-click material creation from AmbientCG"
maintainer = "Nino Filiu <filiunino@gmail.com>"
type = "add-on"
website = "https://github.com/ninofiliu/blender-ambientcg-addon"
tags = ["Import-Export", "Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
network = "Makes calls to AmbientCG"
files = "Import and cache textures to disk"